feat: change to update a change log.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,73 +1,66 @@
 name: Release Notes to Confluence Publisher
-author: Gershon Alvais
-description: Confluence Release BOT. This action will create a release page in confluence with the release notes.
+author: Gershon Alvais & Solid State Networks
+description: Update a change log page in Confluence with the latest release notes.
 branding:
   icon: "book"
-  color: "blue"
+  color: "red"
 
 inputs:
   # Confluence configs
-  spaceId:
-    description: Confluence space id. This is the space where the release page will be created.
+  email:
+    description: Confluence email
+    required: true
+    type: string
+  api_token:
+    description: Confluence API Token
+    required: true
+    type: string
+  host:
+    description: Confluence host name
+    required: true
+    type: string
+  space_key:
+    description: Confluence space key
+    required: true
+    type: string
+  page_id:
+    description: Page ID of the existing Confluence page to update.
     required: true
     type: string
   status:
-    required: true
+    required: false
     type: string
+    default: current
   title:
-    description: Title of the page.  Release tag.
+    description: Title of the page to update.
     required: true
-    type: string
-  parentId:
-    description: Parent page id. The release page will be created under this page.
-    required: true
-    type: string
-  ConfluenceBaseUrl:
-    description: Confluence base url
-    required: true
-    type: string
-  ConfluenceSpaceKey:
-    description: Confluence space key
     type: string
   # Release notes
+  repository:
+    Description: Github repository slug to get release notes from.
+    required: true
+    type: string
   tag:
-    required: true
-    type: string
-  confluence_email:
-    description: 'Confluence Email'
-    required: true
-    type: string
-  confluence_api_token:
-    description: 'Confluence API Token'
-    required: true
-    type: string
-  appName:
-    Description: Name of the app. This will be used in the release notes.
-    required: true
-    type: string
-  repoOwner:
-    Description: Owner of the repository. This will be used to fetch the release notes.
-    required: true
-    type: string
-  repoName:
-    Description: Name of the repository. This will be used to fetch the release notes.
     required: true
     type: string
 
 runs:
   using: "composite"
   steps:
+    - name: Install markdown to HTML converter
+      shell: bash
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y pandoc
+
     - name: Get Release
       id: get-release
       uses: actions/github-script@v7
       with:
         script: |
           const tag = '${{ inputs.tag }}';
-          const release = await github.rest.repos.getReleaseByTag({
-            owner: '${{ inputs.repoOwner }}',
-            repo: '${{ inputs.repoName }}',
-            tag: tag
-          });
+          const [owner, repo] = '${{ inputs.repository }}'.split('/');
+          const release = await github.rest.repos.getReleaseByTag({owner, repo, tag});
           if (!release || !release.data.body) {
               console.error('Invalid release');
               return;
@@ -75,8 +68,39 @@ runs:
           console.log(release.data.body);
           return {
               body: release.data.body,
-              url: `https://github.com/${{ inputs.repoOwner }}/${{ inputs.repoName }}/releases/tag/${tag}`
+              url: `https://github.com/${{ inputs.repository }}/releases/tag/${tag}`
           };
+
+    - name: Get Space ID
+      shell: bash
+      run: |
+        response=$(curl --request GET \
+            --url "https://${{ inputs.host }}/wiki/rest/api/space/${{ inputs.space_key }}" \
+            --user '${{ inputs.email }}:${{ inputs.api_token }}' \
+            --header 'Accept: application/json')
+        echo "Response: $response"
+        spaceId=$(echo "$response" | jq -r '.id')
+        if [ "$spaceId" == "null" ]; then
+          echo "Failed to fetch space id"
+          exit 1
+        fi
+        echo "spaceId=$spaceId" >> $GITHUB_ENV
+
+    - name: Get Current Page Version
+      shell: bash
+      run: |
+        response=$(curl --request GET \
+            --url 'https://${{ inputs.host }}/wiki/api/v2/pages/${{ inputs.page_id }}' \
+            --user '${{ inputs.email }}:${{ inputs.api_token }}' \
+            --header 'Accept: application/json')
+        echo "Response: $response"
+        currentVersion=$(echo "$response" | jq -r '.version.number')
+        if [ "$currentVersion" == "null" ]; then
+          echo "Failed to fetch current page version"
+          exit 1
+        fi
+        nextVersion=$((currentVersion + 1))
+        echo "nextVersion=$nextVersion" >> $GITHUB_ENV
 
     - name: Post Release Notes to Confluence
       id: post_to_confluence
@@ -86,55 +110,77 @@ runs:
         RELEASE_URL: ${{ fromJSON(steps.get-release.outputs.result).url }}
       run: |
         # Add additional line before the content
-        RELEASE_NOTES="✅ New *${{ inputs.appName }}* Release [${{ inputs.tag }}](${RELEASE_URL}) $(date)\n\n${RELEASE_NOTES}"
+        RELEASE_NOTES="# [${{ inputs.tag }}](${RELEASE_URL})\n$(date)\n\n${RELEASE_NOTES}"
 
-        # Remove '##' from RELEASE_NOTES
-        RELEASE_NOTES=$(echo -e "${RELEASE_NOTES}" | sed 's/## //g')
-
-        # Remove extra HTML
-        RELEASE_NOTES=$(echo -e "${RELEASE_NOTES}" | sed -r 's/<[^>]*>//g')
-
-        # Replace markdown links with confluence links
-        RELEASE_NOTES=$(echo -e "${RELEASE_NOTES}" | sed -r 's/\[([^]]+)\]\(([^)]+)\)/[\1|\2]/g')
+        # Reduce size of headings
+        RELEASE_NOTES=$(echo -e "${RELEASE_NOTES}" | sed 's/## /### /g')
 
         # Replace @username with a link to the user's GitHub profile
-        RELEASE_NOTES=$(echo -e "${RELEASE_NOTES}" | sed -r 's/@([^ ]+)/[@\1|https:\/\/github.com\/\1]/g')
+        RELEASE_NOTES=$(echo -e "${RELEASE_NOTES}" | sed -r 's/@([^ ]+)/[@\1](https:\/\/github.com\/\1)/g')
 
-        # Replace '\n' with '<br/>'
-        RELEASE_NOTES=$(echo -e "${RELEASE_NOTES}" | sed 's/\\n/<br\/>/g')
+        # Convert bare PR links to [#number](url)
+        RELEASE_NOTES=$(echo -e "${RELEASE_NOTES}" | sed -r 's@https://github.com/([^/]+)/([^/]+)/pull/([0-9]+)@[#\3](\0)@g')
+        
+        # Convert bare full change log links to [url](url)
+        RELEASE_NOTES=$(echo -e "${RELEASE_NOTES}" | sed -r 's@https://github.com/([^/]+)/([^/]+)/compare/([^/]+)@[\0](\0)@g')
+
+        # Convert Markdown links [text](url) to Confluence format [text|url]
+        RELEASE_NOTES=$(echo -e "${RELEASE_NOTES}" | sed -r 's/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/[\1|\2]/g')
+
+        # Convert markdown to HTML
+        echo "${RELEASE_NOTES}" > release_notes.md
+        pandoc -f markdown -t html release_notes.md -o release_notes.html
+
+        # Convert HTML links to Confluence storage format [text|url]
+        sed -i -E 's#<a href="([^"]+)"[^>]*>([^<]+)</a>#[\2|\1]#g' release_notes.html
+
+        # Read the HTML content into a variable
+        html_content=$(<release_notes.html)
+
+        response=$(curl --request GET \
+            --url 'https://${{ inputs.host }}/wiki/rest/api/content/${{ inputs.page_id }}?expand=body.storage' \
+            --user '${{ inputs.email }}:${{ inputs.api_token }}' \
+            --header 'Accept: application/json')
+        echo "Response: $response"
+        existing_content=$(echo "$response" | jq -r '.body.storage.value')
+        if [ "$existing_content" == "null" ]; then
+          $existing_content=""
+        fi
 
         # Prepare the payload
         payload=$(jq -n \
-        --arg spaceId "${{ inputs.spaceId }}" \
+        --arg spaceId "${{ env.spaceId }}" \
+        --argjson pageId "${{ inputs.page_id }}" \
+        --argjson version "${{ env.nextVersion }}" \
         --arg status "${{ inputs.status }}" \
-        --arg title "Release: ${{ inputs.tag }}" \
-        --arg parentId "${{ inputs.parentId }}" \
-        --arg value "$RELEASE_NOTES" \
+        --arg title "${{ inputs.title }}" \
+        --arg value "${html_content}${existing_content}" \
         '{
             "spaceId": $spaceId,
+            "id": $pageId,
+            "version": {
+              "number": $version
+            },
             "status": $status,
             "title": $title,
-            "parentId": $parentId,
             "body": {
-            "representation": "wiki",
-            "value": $value
+              "representation": "storage",
+              "value": $value
             }
         }'
         )
 
         echo "Payload: $payload"
-        response=$(curl --request POST \
-            --url '${{ inputs.ConfluenceBaseUrl }}/wiki/api/v2/pages' \
-            --user '${{ inputs.confluence_email }}:${{ inputs.confluence_api_token }}' \
+        response=$(curl --request PUT \
+            --url 'https://${{ inputs.host }}/wiki/api/v2/pages/${{ inputs.page_id }}' \
+            --user '${{ inputs.email }}:${{ inputs.api_token }}' \
             --header 'Accept: application/json' \
             --header 'Content-Type: application/json' \
             --data "$payload")
         echo "Response: $response"
-        pageId=$(echo "$response" | jq -r '.id')
-        echo "Page ID: $pageId"
-        if [ "$pageId" == "null" ]; then
-          echo "Failed to create page"
+        responseId=$(echo "$response" | jq -r '.id')
+        echo "Response Page ID: $responseId"
+        if [ "$responseId" == "null" ]; then
+          echo "Failed to update page"
           exit 1
         fi
-        echo "pageId=$pageId" >> $GITHUB_ENV
-        echo "pageId=$pageId" >> $GITHUB_ENV_FILE
